CREATE TABLE IF NOT EXISTS "technical_procedures" (
  "id" serial PRIMARY KEY,
  "name" text NOT NULL,
  "service_id" integer,
  "service_name" text,
  "version" text NOT NULL DEFAULT '1.0',
  "status" text NOT NULL DEFAULT 'rascunho',
  "objective" text,
  "indication" text,
  "contraindication" text,
  "materials" text NOT NULL DEFAULT '[]',
  "tools" text NOT NULL DEFAULT '[]',
  "equipment" text NOT NULL DEFAULT '[]',
  "epis" text NOT NULL DEFAULT '[]',
  "preparation" text,
  "execution" text,
  "curing" text,
  "protection" text,
  "tests" text,
  "acceptance_criteria" text,
  "critical_points" text,
  "common_failures" text,
  "exception_procedure" text,
  "references" text NOT NULL DEFAULT '[]',
  "attachments" text NOT NULL DEFAULT '[]',
  "training_media" text NOT NULL DEFAULT '[]',
  "created_by_user_id" integer,
  "created_by_username" text,
  "approved_by_user_id" integer,
  "approved_by_username" text,
  "approved_at" timestamp,
  "effective_date" timestamp,
  "audit_trail" text NOT NULL DEFAULT '[]',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "checklist_templates" (
  "id" serial PRIMARY KEY,
  "name" text NOT NULL,
  "service_id" integer,
  "service_name" text,
  "procedure_id" integer,
  "phase" text NOT NULL DEFAULT 'Planejamento',
  "version" text NOT NULL DEFAULT '1.0',
  "status" text NOT NULL DEFAULT 'rascunho',
  "items" text NOT NULL DEFAULT '[]',
  "created_by_user_id" integer,
  "created_by_username" text,
  "approved_by_user_id" integer,
  "approved_by_username" text,
  "approved_at" timestamp,
  "audit_trail" text NOT NULL DEFAULT '[]',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "work_order_quality_runs" (
  "id" serial PRIMARY KEY,
  "work_order_id" integer NOT NULL,
  "job_id" integer,
  "procedure_id" integer,
  "procedure_version" text,
  "checklist_template_id" integer,
  "phase" text NOT NULL DEFAULT 'Planejamento',
  "status" text NOT NULL DEFAULT 'pendente',
  "responses" text NOT NULL DEFAULT '{}',
  "required_items_total" integer NOT NULL DEFAULT 0,
  "required_items_done" integer NOT NULL DEFAULT 0,
  "blocking_open_count" integer NOT NULL DEFAULT 0,
  "started_at" timestamp,
  "completed_at" timestamp,
  "completed_by_user_id" integer,
  "completed_by_username" text,
  "audit_trail" text NOT NULL DEFAULT '[]',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "quality_events" (
  "id" serial PRIMARY KEY,
  "work_order_id" integer NOT NULL,
  "job_id" integer,
  "service_name" text,
  "phase" text NOT NULL DEFAULT 'Execução',
  "type" text NOT NULL,
  "severity" text NOT NULL DEFAULT 'normal',
  "status" text NOT NULL DEFAULT 'aberta',
  "description" text NOT NULL,
  "impact_technical" text,
  "impact_financial" real NOT NULL DEFAULT 0,
  "impact_schedule" text,
  "corrective_action" text,
  "resolution" text,
  "photos" text NOT NULL DEFAULT '[]',
  "evidence" text NOT NULL DEFAULT '[]',
  "assigned_to_user_id" integer,
  "assigned_to_username" text,
  "created_by_user_id" integer,
  "created_by_username" text,
  "resolved_by_user_id" integer,
  "resolved_by_username" text,
  "resolved_at" timestamp,
  "audit_trail" text NOT NULL DEFAULT '[]',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);
