CREATE TABLE IF NOT EXISTS material_custody_transfers (
  id SERIAL PRIMARY KEY,
  withdrawal_id INTEGER,
  withdrawal_item_id INTEGER,
  inventory_id INTEGER NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit TEXT NOT NULL DEFAULT 'unid',
  previous_user_id INTEGER,
  previous_username TEXT,
  new_user_id INTEGER NOT NULL,
  new_username TEXT NOT NULL,
  work_order_id INTEGER,
  reason TEXT,
  condition TEXT NOT NULL DEFAULT 'bom',
  evidence_photo TEXT,
  accepted_at TIMESTAMP,
  accepted_by_user_id INTEGER,
  accepted_by_username TEXT,
  status TEXT NOT NULL DEFAULT 'pendente',
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_responsibility_cases (
  id SERIAL PRIMARY KEY,
  withdrawal_id INTEGER,
  withdrawal_item_id INTEGER,
  inventory_id INTEGER,
  product_name TEXT NOT NULL,
  work_order_id INTEGER,
  job_id INTEGER,
  user_id INTEGER,
  username TEXT,
  type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'administrativa',
  status TEXT NOT NULL DEFAULT 'aberta',
  description TEXT NOT NULL,
  evidence TEXT,
  estimated_value REAL NOT NULL DEFAULT 0,
  employee_statement TEXT,
  analysis TEXT,
  decision TEXT,
  financial_status TEXT NOT NULL DEFAULT 'sem_providencia_financeira',
  approved_by_user_id INTEGER,
  approved_by_username TEXT,
  approved_at TIMESTAMP,
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_kits (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'funcao',
  role_name TEXT,
  assigned_user_id INTEGER,
  assigned_username TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho',
  notes TEXT,
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_kit_items (
  id SERIAL PRIMARY KEY,
  kit_id INTEGER NOT NULL,
  inventory_id INTEGER NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  required BOOLEAN NOT NULL DEFAULT TRUE,
  replacement_policy TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tool_maintenance_records (
  id SERIAL PRIMARY KEY,
  inventory_id INTEGER NOT NULL,
  product_name TEXT NOT NULL,
  withdrawal_id INTEGER,
  status TEXT NOT NULL DEFAULT 'aberta',
  maintenance_type TEXT NOT NULL DEFAULT 'corretiva',
  defect_description TEXT,
  provider TEXT,
  estimated_cost REAL NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMP,
  completed_at TIMESTAMP,
  final_condition TEXT,
  photos TEXT,
  released_by_user_id INTEGER,
  released_by_username TEXT,
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_count_audits (
  id SERIAL PRIMARY KEY,
  inventory_id INTEGER NOT NULL,
  product_name TEXT NOT NULL,
  system_quantity INTEGER NOT NULL,
  physical_quantity INTEGER NOT NULL,
  difference INTEGER NOT NULL,
  reason TEXT NOT NULL,
  evidence TEXT,
  status TEXT NOT NULL DEFAULT 'pendente',
  approved_by_user_id INTEGER,
  approved_by_username TEXT,
  approved_at TIMESTAMP,
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_training_guides (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'controle_materiais',
  version TEXT NOT NULL DEFAULT '1.0',
  status TEXT NOT NULL DEFAULT 'rascunho',
  content TEXT NOT NULL,
  media TEXT,
  approved_by_user_id INTEGER,
  approved_by_username TEXT,
  approved_at TIMESTAMP,
  audit_trail TEXT,
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
