CREATE TABLE IF NOT EXISTS visual_brand_kits (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'IMPP_EL Visual Kit',
  brand_name TEXT NOT NULL DEFAULT 'IMPP_EL',
  primary_logo TEXT,
  alternate_logo TEXT,
  light_logo TEXT,
  dark_logo TEXT,
  symbol TEXT,
  watermark TEXT,
  primary_color TEXT NOT NULL DEFAULT '#0f766e',
  secondary_color TEXT NOT NULL DEFAULT '#1d4ed8',
  background_color TEXT NOT NULL DEFAULT '#ffffff',
  typography TEXT NOT NULL DEFAULT 'Fonte do ERP',
  tone_of_voice TEXT DEFAULT 'Profissional, direto e tecnico',
  slogan TEXT,
  institutional_data TEXT DEFAULT '{}',
  contacts TEXT DEFAULT '{}',
  rules TEXT DEFAULT '[]',
  version INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'rascunho',
  approved_by_username TEXT,
  valid_from TIMESTAMP,
  audit_trail TEXT DEFAULT '[]',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visual_media_standards (
  id SERIAL PRIMARY KEY,
  media_type TEXT NOT NULL DEFAULT 'foto',
  purpose TEXT NOT NULL,
  phase TEXT,
  min_quantity INTEGER NOT NULL DEFAULT 0,
  orientation TEXT NOT NULL DEFAULT 'qualquer',
  aspect_ratio TEXT,
  recommended_width INTEGER,
  recommended_height INTEGER,
  min_resolution TEXT,
  quality TEXT,
  duration_seconds INTEGER,
  instructions TEXT DEFAULT '[]',
  required_points TEXT DEFAULT '[]',
  correct_example TEXT,
  incorrect_example TEXT,
  needs_watermark BOOLEAN NOT NULL DEFAULT FALSE,
  requires_authorization BOOLEAN NOT NULL DEFAULT FALSE,
  destination TEXT,
  caption_template TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visual_media_authorizations (
  id SERIAL PRIMARY KEY,
  client_id INTEGER,
  client_name TEXT NOT NULL,
  work_order_id INTEGER,
  authorization_type TEXT NOT NULL DEFAULT 'imagem',
  allowed_images TEXT DEFAULT '[]',
  allowed_channels TEXT DEFAULT '[]',
  purpose TEXT,
  document_data TEXT,
  restrictions TEXT,
  status TEXT NOT NULL DEFAULT 'nao_solicitado',
  revoked_at TIMESTAMP,
  responsible_username TEXT,
  audit_trail TEXT DEFAULT '[]',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visual_assets (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  asset_type TEXT NOT NULL DEFAULT 'imagem',
  source TEXT NOT NULL DEFAULT 'upload',
  original_data TEXT,
  thumbnail_data TEXT,
  derived_data TEXT,
  mime_type TEXT,
  file_size INTEGER NOT NULL DEFAULT 0,
  checksum TEXT,
  client_id INTEGER,
  work_order_id INTEGER,
  service_name TEXT,
  phase TEXT,
  purpose TEXT,
  authorization_id INTEGER,
  authorization_status TEXT NOT NULL DEFAULT 'nao_solicitado',
  tags TEXT DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'rascunho',
  processing_status TEXT NOT NULL DEFAULT 'pendente',
  processing_notes TEXT,
  metadata TEXT DEFAULT '{}',
  audit_trail TEXT DEFAULT '[]',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visual_templates (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  template_type TEXT NOT NULL,
  channel TEXT,
  format TEXT,
  brand_kit_id INTEGER,
  config TEXT NOT NULL DEFAULT '{}',
  text_template TEXT,
  status TEXT NOT NULL DEFAULT 'rascunho',
  version INTEGER NOT NULL DEFAULT 1,
  approved_by_username TEXT,
  audit_trail TEXT DEFAULT '[]',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visual_compositions (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  composition_type TEXT NOT NULL DEFAULT 'antes_depois',
  before_asset_id INTEGER,
  after_asset_id INTEGER,
  template_id INTEGER,
  brand_kit_id INTEGER,
  work_order_id INTEGER,
  client_id INTEGER,
  service_name TEXT,
  format TEXT NOT NULL DEFAULT 'whatsapp',
  caption TEXT,
  output_data TEXT,
  authorization_status TEXT NOT NULL DEFAULT 'nao_solicitado',
  status TEXT NOT NULL DEFAULT 'rascunho',
  audit_trail TEXT DEFAULT '[]',
  created_by_user_id INTEGER,
  created_by_username TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
